apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      containers:
        - name: dashboard-app
          image: sadiadevopsacr786.azurecr.io/dashboard-app:v1
          ports:
            - containerPort: 3000